# Site settings
lang: en
title: Briggs Library Book Search Guide
description: >
  The guide website for Briggs Library database searching
baseurl: "/briggs-book-search-guide"
url: "https://albright220.github.io"
permalink: pretty

# Build settings
remote_theme: chrisrhymes/bulma-clean-theme

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
